version: 2
jobs:
  build:
    branches:
      - master
    docker:
      - image: fedora:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Listing directory
          command: pwd && ls -lah
      - run:
          name: Installing Dependencies
          command: dnf install git -y 
      - run:
          name: Configuring github
          command: git config --global user.email "zcristian1913@hotmail.com" && git config --global user.name "pystudent1913"
      - run:
          name: Checkout to gh-pages
          command: git checkout -b gh-pages
      - run:
          name: Remove README and .circleci
          command: rm -r README.md .circleci
      - run:
          name: Extract src content
          command: mv src/* .
      - run:
          name: Remove old src file
          command: rm -r src
      - run:
          name: Git-add-tmr
          command: git add .
      - run:
          name: Git-commit-tmr
          command: git commit -m "Circle CI"
      - run:
          name: Pushing
          command: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push -f origin gh-pages

